name: Terraform CD

on:
  push:
    branches: [ "main" ]


jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        name: Checkout repository

      - name: Create tfvars file
        run: |
        cat <<EOF > terraform.tfvars
        instance_name = "${{ inputs.instance_name }}"
        instance_type = "${{ inputs.instance_type }}"
        region = "${{ inputs.region }}"
        EOF

      - name: Terraform Init
        run: terraform init
      
      

  